### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lelcuk**
i followed the readme some staff did not work...
see minor proposed updates
tnx

### CODE REVIEW

**Comment by krisek** [comment]
Many thanks for this update, much appreciated. One point: it really didn't work without python-virtualenv? On my development box I don't have the package and installation works.

**Comment by lelcuk** [comment]
yes, somehow on my pi (stretch) it needed  python-virtualenv... have no
idea why?.... I am growing tired with this 2 - 3 schism ....
anyway now fighting with uwsgi not finding python 3 plugin chhhh
tnx

Alon
-------------------
Alon Lelcuk
Israel: +972 (54) 462-2165
USA:    +1 (646) 481-1305
[image: image.png]

**Comment by krisek** [comment]
On buster it is installed with these packages:

> dpkg -S /usr/lib/uwsgi/plugins
uwsgi-plugin-python3, uwsgi-core, uwsgi-plugin-python: /usr/lib/uwsgi/plugins

And then in app.ini
[uwsgi]
...
plugins-dir = /usr/lib/uwsgi/plugins
...

**Comment by krisek** [comment]
I'll add a comment that python-virtualenv might be only needed on Raspbian. Thanks a lot again.

**Pull request merged**
